"""Initial schema with all models

Revision ID: 4eb3d03ed491
Revises: 
Create Date: 2025-12-01 13:08:44.045246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '4eb3d03ed491'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_cache',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('query_hash', sa.String(length=255), nullable=False),
    sa.Column('data_source_ids', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('computation_time_ms', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_cache_cache_key'), 'insight_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_insight_cache_expires_at'), 'insight_cache', ['expires_at'], unique=False)
    op.create_index('ix_insight_cache_expires_at_created_at', 'insight_cache', ['expires_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_insight_cache_id'), 'insight_cache', ['id'], unique=False)
    op.create_index(op.f('ix_insight_cache_query_hash'), 'insight_cache', ['query_hash'], unique=False)
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('CSV', 'EXCEL', 'POSTGRESQL', 'MYSQL', 'SQLSERVER', 'API', 'S3', 'GOOGLE_SHEETS', name='sourcetype'), nullable=False),
    sa.Column('connection_config', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('schema_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_connected_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_refreshed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('refresh_schedule', sa.String(length=100), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_is_active'), 'data_sources', ['is_active'], unique=False)
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=True)
    op.create_index(op.f('ix_data_sources_source_type'), 'data_sources', ['source_type'], unique=False)
    op.create_table('queries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('natural_language_query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('data_sources_used', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CACHED', name='querystatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parent_query_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['parent_query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_created_at'), 'queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_queries_id'), 'queries', ['id'], unique=False)
    op.create_index(op.f('ix_queries_status'), 'queries', ['status'], unique=False)
    op.create_index(op.f('ix_queries_user_id'), 'queries', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alert_type', sa.Enum('THRESHOLD', 'TREND', 'ANOMALY', 'COMPARATIVE', name='alerttype'), nullable=False),
    sa.Column('condition_config', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('data_source_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('check_frequency', sa.String(length=100), nullable=False),
    sa.Column('notification_channels', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_triggered_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_check_frequency'), 'alerts', ['check_frequency'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_active'), 'alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('query_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.Enum('QUICK_INSIGHT', 'EXECUTIVE_SUMMARY', 'DEEP_DIVE', 'ALERT_REPORT', name='reporttype'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('visualizations', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('format', sa.Enum('HTML', 'PDF', 'MARKDOWN', 'PPTX', name='reportformat'), nullable=False),
    sa.Column('report_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('shared_with', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_is_scheduled'), 'reports', ['is_scheduled'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('alert_executions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('alert_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.Enum('TRIGGERED', 'NOT_TRIGGERED', 'ERROR', name='executionstatus'), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_executions_alert_id'), 'alert_executions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_executions_executed_at'), 'alert_executions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_alert_executions_id'), 'alert_executions', ['id'], unique=False)
    op.create_table('report_versions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('report_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_versions_id'), 'report_versions', ['id'], unique=False)
    op.create_index(op.f('ix_report_versions_report_id'), 'report_versions', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_versions_report_id'), table_name='report_versions')
    op.drop_index(op.f('ix_report_versions_id'), table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index(op.f('ix_alert_executions_id'), table_name='alert_executions')
    op.drop_index(op.f('ix_alert_executions_executed_at'), table_name='alert_executions')
    op.drop_index(op.f('ix_alert_executions_alert_id'), table_name='alert_executions')
    op.drop_table('alert_executions')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_scheduled'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_active'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_check_frequency'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_queries_user_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_status'), table_name='queries')
    op.drop_index(op.f('ix_queries_id'), table_name='queries')
    op.drop_index(op.f('ix_queries_created_at'), table_name='queries')
    op.drop_table('queries')
    op.drop_index(op.f('ix_data_sources_source_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_is_active'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_insight_cache_query_hash'), table_name='insight_cache')
    op.drop_index(op.f('ix_insight_cache_id'), table_name='insight_cache')
    op.drop_index('ix_insight_cache_expires_at_created_at', table_name='insight_cache')
    op.drop_index(op.f('ix_insight_cache_expires_at'), table_name='insight_cache')
    op.drop_index(op.f('ix_insight_cache_cache_key'), table_name='insight_cache')
    op.drop_table('insight_cache')
    # ### end Alembic commands ###
